#!/bin/bash

#set -x

shopt -s expand_aliases # Must set this option, else script will not expand aliases.

alias bogglecomp='javac -sourcepath sources -d classes sources/boggle/*.java'
alias motscomp='javac -sourcepath sources -d classes sources/boggle/mots/*.java'
alias uicomp='javac -sourcepath sources -d classes sources/boggle/ui/*.java'
alias jeucomp='javac -sourcepath sources -d classes sources/boggle/jeu/*.java'

bogglecomp;echo "boggle : $?";
motscomp;echo "mots : $?";
uicomp;echo "ui : $?";
jeucomp;echo "jeu : $?";
